package com.n11.bootcamp.ecommerce.order.entity;

public enum SagaState {
    INITIATED,
    STOCK_RESERVED,
    PROMOTION_APPLIED,
    PROMOTION_FAILED,
    PAYMENT_REQUESTED,
    PAYMENT_PENDING_USER,
    PAYMENT_FAILED,
    COMMIT_REQUESTED,
    COMPENSATING_PROMOTION,
    COMPENSATING_STOCK,
    COMPLETED,
    FAILED
}