CREATE DATABASE product_db;
CREATE DATABASE stock_db;
CREATE DATABASE order_db;
CREATE DATABASE payment_db;
CREATE DATABASE user_db;
CREATE DATABASE review_db;
CREATE DATABASE promotion_db;
CREATE DATABASE keycloak_db;